name: pytest

on: [push, pull_request]

jobs:
  python-pytest:
    name: Python pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pytest
      - name: Run pytest
        run: |
          python -m pytest -vv
